baseURL: 'https://dariusduta.dev/'
languageCode: 'en-gb'
title: 'Darius Duta'
pluralizeListTitles: false

googleAnalytics: G-EYY3066F76

markup:
  tableOfContents:
    ordered: false
    startLevel: 1
    endLevel: 3
