
metadata:
  robots: index, follow
  canonical: https://dariusduta.dev
  description: I am Darius Duta, a full-stack web developer with a focus on AWS cloud and automations.

  ogType: website
  ogTitle: Darius Duta | Software Engineer
  ogUrl: https://dariusduta.dev

assets:
  favicon: icons/favicon.ico
  favicon16x16: icons/favicon.ico
  favicon32x32: icons/favicon.ico
  apple_touch_icon: icons/favicon.ico
  theme_color: "#2e2e33"
  msapplication_TileColor: "#2e2e33"

  profilePic: images/profile_pic.webp

features:
  showScrollToTop: true
