Resources:
  InfraHostedZoneBDAFBEA7:
    Type: AWS::Route53::HostedZone
    Properties:
      HostedZoneConfig:
        Comment: dariusduta.dev public zone
      Name: dariusduta.dev.
    Metadata:
      aws:cdk:path: RouteStack/InfraHostedZone/Resource
  CDKMetadata:
    Type: AWS::CDK::Metadata
    Properties:
      Analytics: v2:deflate64:H4sIAAAAAAAA/zPSMzHQM1BMLC/WTU7J1s3JTNKrDi5JTM7WAQrFF+WXlqSaGutVe+QXl6SmROXnpeo4p+UheLUgblBqcX5pUTKQk5efkqqXVaxfZmimZ2iqZ6iYVZyZqVtUmleSmZuqFwShAcX7JihzAAAA
    Metadata:
      aws:cdk:path: RouteStack/CDKMetadata/Default
Parameters:
  BootstrapVersion:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /cdk-bootstrap/hnb659fds/version
    Description: Version of the CDK Bootstrap resources in this environment, automatically retrieved from SSM Parameter Store. [cdk:skip]
Rules:
  CheckBootstrapVersion:
    Assertions:
      - Assert:
          Fn::Not:
            - Fn::Contains:
                - - "1"
                  - "2"
                  - "3"
                  - "4"
                  - "5"
                - Ref: BootstrapVersion
        AssertDescription: CDK bootstrap stack version 6 required. Please run 'cdk bootstrap' with a recent version of the CDK CLI.

